# GCC version mismatch: noble vs noble
FROM ubuntu:noble

RUN apt-get update && apt-get install gcc-multilib git ca-certificates wget file -yq --no-install-recommends

RUN wget https://go.dev/dl/go1.22.3.linux-amd64.tar.gz && \
    rm -rf /usr/local/go && \
    tar -C /usr/local -xzf go1.22.3.linux-amd64.tar.gz && \
    export PATH=$PATH:/usr/local/go/bin
ENV PATH=$PATH:/usr/local/go/bin


# reference build. v1.14.3 bumped ubuntu to noble: https://github.com/ethereum/go-ethereum/pull/29723
# TODO generalise to take in a certain geth version...
RUN wget https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.14.3-ab48ba42.tar.gz && tar -xvf geth-linux-amd64-1.14.3-ab48ba42.tar.gz && \
    cd geth-linux-amd64-1.14.3-ab48ba42 && \
    strip --remove-section .note.go.buildid --remove-section .note.gnu.build-id geth && \
    mkdir -p /bin && mv geth /bin/geth-reference

# reproducing build
RUN git clone --depth 1 --branch v1.14.3 https://github.com/ethereum/go-ethereum.git && cd go-ethereum && git fetch && \
    git checkout ab48ba42f4f34873d65fd1737fabac5c680baff6 && \
    CGO_ENABLED=1 go run ./build/ci.go install -dlgo ./cmd/geth/ && \
    strip --remove-section .note.go.buildid --remove-section .note.gnu.build-id ./build/bin/geth && \
    mv ./build/bin/geth /bin/geth-reproduce


# TODO generalise to take in a script...
RUN cd /bin && echo "# geth reference build" > /non-determinism.md && \
    go version -m geth-reference | head -n 1 >> /non-determinism.md && \
    echo "Running \`readelf -p .comment geth-reference\`..." >> /non-determinism.md && \
    readelf -p .comment geth-reference >> /non-determinism.md || echo "Error." >> /non-determinism.md


RUN cd /bin && echo "# geth reproducing build" >> /non-determinism.md && \
    go version -m geth-reproduce | head -n 1 >> /non-determinism.md && \
    echo "Running \`readelf -p .comment geth-reproduce\`..." >> /non-determinism.md && \
    readelf -p .comment geth-reproduce >> /non-determinism.md || echo "Error." >> /non-determinism.md && \
    echo "Built in OS:"  >> /non-determinism.md && \
    cat /etc/os-release | head -n 4 >> /non-determinism.md
