FROM ubuntu:bionic

RUN apt-get update && apt-get install gcc-multilib git ca-certificates wget -yq --no-install-recommends

RUN wget https://go.dev/dl/go1.22.3.linux-amd64.tar.gz && \
    rm -rf /usr/local/go && \
    tar -C /usr/local -xzf go1.22.3.linux-amd64.tar.gz && \
    export PATH=$PATH:/usr/local/go/bin
ENV PATH=$PATH:/usr/local/go/bin


# reference build. v1.14.3, may 9 2024
# TODO generalise to take in a certain geth version...
RUN wget https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.14.3-ab48ba42.tar.gz && tar -xvf geth-linux-amd64-1.14.3-ab48ba42.tar.gz && \
    cd geth-linux-amd64-1.14.3-ab48ba42 && strip --remove-section .note.go.buildid --remove-section .note.gnu.build-id geth && \
    mkdir -p /bin && mv geth /bin/geth-reference

# reproducing build
RUN git clone --depth 1 --branch v1.14.3 https://github.com/ethereum/go-ethereum.git && cd go-ethereum && git fetch && \
    git checkout ab48ba42f4f34873d65fd1737fabac5c680baff6 && \
    CGO_ENABLED=1 go run ./build/ci.go install -dlgo ./cmd/geth/ && \
    strip --remove-section .note.go.buildid --remove-section .note.gnu.build-id ./build/bin/geth && \
    mv ./build/bin/geth /bin/geth-reproduce


# TODO generalise to take in a script...
RUN cd /bin && echo "# geth reference build" > /non-determinism.md && \
    go version -m geth-reference | head -n 1 >> /non-determinism.md && \
    VCS_TIME_1=$(go version -m geth-reference | grep "vcs.time") && echo $VCS_TIME_1 >> /non-determinism.md && \
    DATE_1=$(echo $VCS_TIME_1 | awk -F= -F'[=-:TZ]' '{printf "%s%s%s\n", $2, $3, $4}') && \
    echo "Running \`strings -f geth-reference | grep $DATE_1\`..." >> /non-determinism.md && \
    strings -f geth-reference | grep $DATE_1 >> /non-determinism.md || echo "No match." >> /non-determinism.md

RUN cd /bin && echo "# geth reproducing build" >> /non-determinism.md && \
    go version -m geth-reproduce | head -n 1 >> /non-determinism.md && \
    VCS_TIME_2=$(go version -m geth-reproduce | grep "vcs.time") && echo $VCS_TIME_2 >> /non-determinism.md && \
    DATE_2=$(echo $VCS_TIME_2 | awk -F= -F'[=-:TZ]' '{printf "%s%s%s\n", $2, $3, $4}') && \
    echo "Running \`strings -f geth-reproduce | grep $DATE_2\`..." >> /non-determinism.md && \
    strings -f geth-reproduce | grep $DATE_2 >> non-determinism.md || echo "No match." >> /non-determinism.md 