FROM ubuntu:bionic

RUN apt-get update && apt-get install gcc-multilib git ca-certificates wget -yq --no-install-recommends

RUN wget https://go.dev/dl/go1.21.6.linux-amd64.tar.gz && \
    rm -rf /usr/local/go && \
    tar -C /usr/local -xzf go1.21.6.linux-amd64.tar.gz && \
    export PATH=$PATH:/usr/local/go/bin
ENV PATH=$PATH:/usr/local/go/bin


# reference build
RUN wget https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.13.15-c5ba367e.tar.gz && tar -xvf geth-linux-amd64-1.13.15-c5ba367e.tar.gz && \
    cd geth-linux-amd64-1.13.15-c5ba367e && strip --remove-section .note.go.buildid --remove-section .note.gnu.build-id geth && \
    mkdir -p /bin && mv geth /bin/geth-reference

# reproducing build
RUN git clone --branch master https://github.com/ethereum/go-ethereum.git && cd go-ethereum && git fetch && \
    git checkout c5ba367eb6232e3eddd7d6226bfd374449c63164 && \
    CGO_ENABLED=1 /usr/local/go/bin/go run ./build/ci.go install -dlgo ./cmd/geth/
RUN cd go-ethereum/build/bin && strip --remove-section .note.go.buildid --remove-section .note.gnu.build-id geth
RUN	mv go-ethereum/build/bin/geth /bin/geth-reproduce
#RUN go version >> /go-env-info.txt && go env >> /go-env-info.txt
#RUN cat /etc/os-release >> os-info.txt

RUN cd /bin && echo "# geth reference build" > /non-determinism.md && \
    go version -m geth-reference | head -n 1 >> /non-determinism.md && \
    VCS_TIME_1=$(go version -m geth-reference | grep "vcs.time") && echo $VCS_TIME_1 >> /non-determinism.md && \
    DATE_1=$(echo $VCS_TIME_1 | awk -F= -F'[=-:TZ]' '{printf "%s%s%s\n", $2, $3, $4}') && \
    echo "running 'strings -f geth-reference | grep $DATE_1':" >> /non-determinism.md && \
    strings -f geth-reference | grep $DATE_1 >> /non-determinism.md || echo "No match." >> /non-determinism.md

RUN cd /bin && echo "# geth reproducing build" >> /non-determinism.md && \
    go version -m geth-reproduce | head -n 1 >> /non-determinism.md && \
    VCS_TIME_1=$(go version -m geth-reproduce | grep "vcs.time") && echo $VCS_TIME_1 >> /non-determinism.md && \
    DATE_1=$(echo $VCS_TIME_1 | awk -F= -F'[=-:TZ]' '{printf "%s%s%s\n", $2, $3, $4}') && \
    echo "running 'strings -f geth-reproduce | grep $DATE_1':" >> /non-determinism.md && \
    strings -f geth-reproduce | grep $DATE_1 >> non-determinism.md || echo "No match." >> /non-determinism.md 